let data = JSON.stringify(
{
  "zen": "Favor focus over features.",
  "hook_id": 303774976,
  "hook": {
    "type": "Repository",
    "id": 303774976,
    "name": "web",
    "active": true,
    "events": [
      "member",
      "pull_request",
      "push",
      "team_add"
    ],
    "config": {
      "content_type": "json",
      "insecure_ssl": "0",
      "secret": "********",
      "url": "https://google.com/api/hook/github"
    },
    "updated_at": "2021-06-22T03:51:19Z",
    "created_at": "2021-06-22T03:51:19Z",
    "url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/hooks/303774976",
    "test_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/hooks/303774976/test",
    "ping_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/hooks/303774976/pings",
    "last_response": {
      "code": null,
      "status": "unused",
      "message": null
    }
  },
  "repository": {
    "id": 337008728,
    "node_id": "MDEwOlJlcG9zaXRvcnkzMzcwMDg3Mjg=",
    "name": "test-sun-ci",
    "full_name": "dangcq-1093/test-sun-ci",
    "private": false,
    "owner": {
      "login": "dangcq-1093",
      "id": 78715700,
      "node_id": "MDQ6VXNlcjc4NzE1NzAw",
      "avatar_url": "https://avatars.githubusercontent.com/u/78715700?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dangcq-1093",
      "html_url": "https://github.com/dangcq-1093",
      "followers_url": "https://api.github.com/users/dangcq-1093/followers",
      "following_url": "https://api.github.com/users/dangcq-1093/following{/other_user}",
      "gists_url": "https://api.github.com/users/dangcq-1093/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dangcq-1093/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dangcq-1093/subscriptions",
      "organizations_url": "https://api.github.com/users/dangcq-1093/orgs",
      "repos_url": "https://api.github.com/users/dangcq-1093/repos",
      "events_url": "https://api.github.com/users/dangcq-1093/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dangcq-1093/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/dangcq-1093/test-sun-ci",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/dangcq-1093/test-sun-ci",
    "forks_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/forks",
    "keys_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/teams",
    "hooks_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/hooks",
    "issue_events_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/issues/events{/number}",
    "events_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/events",
    "assignees_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/assignees{/user}",
    "branches_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/branches{/branch}",
    "tags_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/tags",
    "blobs_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/languages",
    "stargazers_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/stargazers",
    "contributors_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/contributors",
    "subscribers_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/subscribers",
    "subscription_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/subscription",
    "commits_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/contents/{+path}",
    "compare_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/merges",
    "archive_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/downloads",
    "issues_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/issues{/number}",
    "pulls_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/labels{/name}",
    "releases_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/releases{/id}",
    "deployments_url": "https://api.github.com/repos/dangcq-1093/test-sun-ci/deployments",
    "created_at": "2021-02-08T08:33:36Z",
    "updated_at": "2021-05-20T06:35:17Z",
    "pushed_at": "2021-06-22T03:41:48Z",
    "git_url": "git://github.com/dangcq-1093/test-sun-ci.git",
    "ssh_url": "git@github.com:dangcq-1093/test-sun-ci.git",
    "clone_url": "https://github.com/dangcq-1093/test-sun-ci.git",
    "svn_url": "https://github.com/dangcq-1093/test-sun-ci",
    "homepage": null,
    "size": 85,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "PHP",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 11,
    "license": null,
    "forks": 0,
    "open_issues": 11,
    "watchers": 0,
    "default_branch": "master"
  },
  "sender": {
    "login": "dangcq-1093",
    "id": 78715700,
    "node_id": "MDQ6VXNlcjc4NzE1NzAw",
    "avatar_url": "https://avatars.githubusercontent.com/u/78715700?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dangcq-1093",
    "html_url": "https://github.com/dangcq-1093",
    "followers_url": "https://api.github.com/users/dangcq-1093/followers",
    "following_url": "https://api.github.com/users/dangcq-1093/following{/other_user}",
    "gists_url": "https://api.github.com/users/dangcq-1093/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dangcq-1093/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dangcq-1093/subscriptions",
    "organizations_url": "https://api.github.com/users/dangcq-1093/orgs",
    "repos_url": "https://api.github.com/users/dangcq-1093/repos",
    "events_url": "https://api.github.com/users/dangcq-1093/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dangcq-1093/received_events",
    "type": "User",
    "site_admin": false
  }
}
);
console.log(data);